load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "KalmanMono",
    srcs = ["main0.cpp"],
    deps = [
       "@eigen_repo//:eigen",
    ],
)